---
title: "Fibonacci and k-Subsecting Recursive Feature Elimination: Supplement"
output: 
  html_notebook: 
    code_folding: hide
    number_sections: yes
    toc: yes
    toc_depth: 2
---

```{r libraries, message=FALSE, warning=FALSE}
library(knitr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(plotly)
library(DT)
library(ggthemes)
library(PMCMR)
library(scmamp)

knitr::opts_chunk$set(dpi=96, results = "asis")
knitr::knit_hooks$set(inline = function(x) {
  prettyNum(x, big.mark=",")
})
SAVE_EPS = F
```

```{r functions}
prettyTable <- function(table_df, round_columns=numeric(), round_digits=3, make_plot=T) {
    DT::datatable(table_df, style="bootstrap", filter = "top", rownames = FALSE, extensions = "Buttons",
                  options = list(dom = 'Bfrtip', buttons = c('copy', 'csv', 'excel', 'pdf', 'print'))) %>%
    formatRound(round_columns, round_digits)
}

reportFriedman <- function(df, classifier, metric, metric_function, metric_direction=1, make_plot = T){
    averages = data.frame(df) %>%
        select(-c(Attributes, Number.of.classes, Min.class.examples, Max.class.examples)) %>%
        group_by(Dataset, Classifier, Feature.selector) %>%
        summarise_all(metric_function, na.rm=T) %>%
        data.frame() %>%
        filter(Feature.selector != 'All', Classifier == classifier) %>%
        select_("Dataset", "Feature.selector", metric) %>%
        spread("Feature.selector", metric) %>%
        select(-Dataset) %>%
        select(`FRFE`, `RFE-log`, `3-SRFE`, `RFE-log-3`, `5-SRFE`, `RFE-log-5`, `10-SRFE`, `RFE-log-10`) %>%
        data.matrix()
    
    if (metric_direction == 1) {
      averages_r = -averages
      averages_t = averages
    } else {
      averages_r = averages
      averages_t = -averages
    }
    ranks <- t(apply(averages_r, 1, rank))
    ranks <- ranks[,order(colMeans(ranks, na.rm=TRUE))]

    cat("<hr><strong>Friedman rank sum test</strong><br />")
    fTest <- friedman.test(averages_t)
    testResult <- capture.output(print(fTest))
    cat(testResult[5])
    cat("\r\n")
    mean_ranks <- t(colMeans(ranks, na.rm=TRUE))
    print(kable(mean_ranks, digits = 2))
    cat("\r\n")
    
    if (make_plot){
        print(plotCD(results.matrix = averages_t, alpha = 0.05))
    }

    cat("<hr>")
    mean_ranks_df <- data.frame(`FRFE` = mean_ranks[1, "FRFE"], `RFE-log` = mean_ranks[1, "RFE-log"], `3-SRFE` = mean_ranks[1, "3-SRFE"], `RFE-log-3` = mean_ranks[1, "RFE-log-3"], `5-SRFE` = mean_ranks[1, "5-SRFE"], `RFE-log-5` = mean_ranks[1, "RFE-log-5"], `10-SRFE` = mean_ranks[1, "10-SRFE"], `RFE-log-10` = mean_ranks[1, "RFE-log-10"], `p-value` = fTest$p.value)
    mean_ranks_df
}
```


# Results summary

## Raw results

```{r raw summary}
df <- read.csv("Benchmarks.csv", na.strings = c("?", "", "-")) %>%
    mutate(Dataset = as.character(Dataset), Classifier = as.character(Classifier), Selected.num = as.character(Selected.num)) %>%
    select(-c(Start.date, Selector.params, Scorer, Grid.scores, Selected.features))


df$Dataset <- substr(df$Dataset, 1, nchar(df$Dataset)-4)
df$Dataset <- as.factor(df$Dataset)

df$Classifier[startsWith(df$Classifier, "SVC")] <- "SVM"
df$Classifier[startsWith(df$Classifier, "Random")] <- "RF"
df$Classifier[startsWith(df$Classifier, "Logistic")] <- "LR"
df$Classifier[startsWith(df$Classifier, "LGBM")] <- "GBM"
df$Classifier <- as.factor(df$Classifier)

df$Selected.num[df$Selected.num == "error"] <- NA
df$Selected.num <- as.numeric(df$Selected.num)

prettyTable(df, c(9, 11:15))
```

## Datasets

```{r dataset summary}
datasets_df <- df %>%
  select(Dataset, Examples, Attributes, Number.of.classes, Min.class.examples, Max.class.examples) %>%
  distinct()
  
prettyTable(datasets_df)
```

## Mean cross-validation scores

```{r cv summary, warning=F}
cv_df <- df %>%
  select(-c(Attributes, Number.of.classes, Min.class.examples, Max.class.examples)) %>%
  group_by(Dataset, Classifier, Feature.selector) %>%
  summarise_all(mean, na_rm=T)
  

prettyTable(cv_df, c(5, 8:12))
```

# Comparisons and statistical tests {.tabset}

```{r, results="asis"}
classifiers <- as.character(unique(cv_df$Classifier))
metrics <- c("Selected.num", "Selected.num", "Accuracy", "Kappa", "Macro.recall", "G.mean", "Processing.time")
metric_functions <- c(mean, sd, mean, mean, mean, mean, mean)
mertric_headers <-c("Number of selected features", "Standard deviation of number of selected features", "Accuracy", "Kappa", "Macro recall", "G-mean", "Processing time")
metric_direction <- c(-1, -1, 1, 1, 1, 1, -1)

friedman_df <- data.frame(Metric = character(), Classifier = character(), `FRFE` = numeric(), `RFE-log` = numeric(), `3-SRFE` = numeric(), `RFE-log-3` = numeric(), `5-SRFE` = numeric(), `RFE-log-5` = numeric(), `10-SRFE` = numeric(), `RFE-log-10` = numeric(), `p-value` = numeric())

for (i in seq_along(metrics)){
  cat(paste0("## ", mertric_headers[i],"\r\n\r\n"))
  for (classifier in classifiers){
    cat(paste0("### ", classifier,"\r\n\r\n"))
    mean_ranks <- reportFriedman(df, classifier, metrics[i], metric_functions[i], metric_direction[i], make_plot = F)
    mean_df <- data.frame(Metric = mertric_headers[i], Classifier = classifier, `FRFE` = mean_ranks$FRFE, `RFE-log` = mean_ranks$RFE.log, `3-SRFE` = mean_ranks$X3.SRFE, `RFE-log-3` = mean_ranks$RFE.log.3, `5-SRFE` = mean_ranks$X5.SRFE, `RFE-log-5` = mean_ranks$RFE.log.5, `10-SRFE` = mean_ranks$X10.SRFE, `RFE-log-10` = mean_ranks$RFE.log.10, `p-value` = mean_ranks$p.value)
    friedman_df <- rbind(friedman_df, mean_df)
  }
}

```

## Friedman tests summary

```{r freidmanSummary}
prettyTable(friedman_df, 3:ncol(friedman_df), 3)
```


# Feature selection plots

```{r feature plots}
df_grid <- read.csv("GridScores.csv", na.strings = c("?", "", "-")) %>% 
  mutate(Dataset = as.character(Dataset), Classifier = as.character(Classifier))
df_grid$Dataset <- substr(df_grid$Dataset, 1, nchar(df_grid$Dataset)-4)
df_grid$Dataset <- as.factor(df_grid$Dataset)

df_grid$Classifier[startsWith(df_grid$Classifier, "SVC")] <- "SVM"
df_grid$Classifier[startsWith(df_grid$Classifier, "Random")] <- "RF"
df_grid$Classifier[startsWith(df_grid$Classifier, "Logistic")] <- "LR"
df_grid$Classifier[startsWith(df_grid$Classifier, "LGBM")] <- "GBM"
df_grid$Classifier <- as.factor(df_grid$Classifier)

df_grid$Feature.selector = factor(df_grid$Feature.selector,levels(df_grid$Feature.selector)[c(4,2,3,1,5,7,8,6)])

df_grid$Type <- as.character(df_grid$Feature.selector)
df_grid$Type[df_grid$Type == "FRFE" | df_grid$Type == "3-SRFE" | df_grid$Type == "5-SRFE" | df_grid$Type == "10-SRFE"] <- "FRFE/k-SRFE"
df_grid$Type[df_grid$Type != "FRFE/k-SRFE"] <- "RFE"
df_grid$Type <- as.factor(df_grid$Type)


cbPalette <- c("#a6cee3", "#b2df8a", "#fb9a99", "#fdbf6f", "#1f78b4", "#33a02c", "#e31a1c", "#ff7f00")

for (dataset in unique(df_grid$Dataset)){
  plot_df <- df_grid %>% filter(Dataset == dataset)
  p <- ggplot(plot_df, aes(Feature.num, Accuracy, color=Feature.selector)) + geom_point(alpha=0.6) + facet_grid(Classifier~Type) + theme_bw() + scale_color_manual(values=cbPalette, name="Selector") + xlab("Number of features")
  ggsave(paste0(dataset, ".svg"), plot = p, dpi = 300, width=8, height=4, units = "in")
  ggsave(paste0(dataset, ".png"), plot = p, dpi = 300, width=8, height=4, units = "in")
  print(p + ggtitle(dataset))
}
```





